name: Build ImmortalWrt AX18 (Final)

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # 使用你自己的 ImmortalWrt 仓库
  REPO_URL: https://github.com/VIKINGYFY/immortalwrt
  REPO_BRANCH: main
  CONFIG_FILE: ax18nano.config
  FIRMWARE_NAME: immortalwrt-ax18
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment and install dependencies
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison gawk \
            libncurses5-dev libncursesw5-dev zlib1g-dev gettext \
            libssl-dev python3 python3-distutils python3-setuptools \
            rsync unzip wget git subversion ccache

      - name: Detect CPU cores
        run: echo "THREAD_COUNT=$(nproc)" >> $GITHUB_ENV

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            ccache
            immortalwrt/dl
          key: ${{ runner.os }}-immortalwrt-${{ hashFiles('ax18nano.config', 'custom-files/**') }}
          restore-keys: |
            ${{ runner.os }}-immortalwrt-

      - name: Prepare ccache
        run: |
          mkdir -p ccache
          echo "PATH=$(pwd)/ccache:$PATH" >> $GITHUB_ENV
          ccache -M 5G
          ccache -s

      - name: Clone your ImmortalWrt source
        run: git clone --depth=1 -b "$REPO_BRANCH" "$REPO_URL" immortalwrt

      - name: Update feeds
        working-directory: ./immortalwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load custom config and files
        run: |
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "ERROR: Config file $CONFIG_FILE not found!"
            exit 1
          fi
          cp "$CONFIG_FILE" ./immortalwrt/.config

          if [ -d "custom-files" ]; then
            echo "Custom files found. Copying to build root."
            mkdir -p ./immortalwrt/files/
            cp -rf ./custom-files/* ./immortalwrt/files/
          else
            echo "No custom files found. Skipping."
          fi

          cd immortalwrt
          make defconfig

      - name: Download package sources
        working-directory: ./immortalwrt
        run: |
          make download -j"${THREAD_COUNT}"
          find dl -size -1024c -exec rm -f {} \;

      - name: Build firmware
        id: compile
        working-directory: ./immortalwrt
        run: |
          make -j"${THREAD_COUNT}" || make -j1 V=s

      - name: Organize firmware files
        if: steps.compile.outcome == 'success'
        run: |
          cd immortalwrt/bin/targets/*/*
          rm -rf packages
          echo "FIRMWARE_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        if: steps.compile.outcome == 'success'
        with:
          name: ${{ env.FIRMWARE_NAME }}
          path: ${{ env.FIRMWARE_PATH }}
