name: Build AX18 OpenWrt

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3 python3-setuptools python3-pip rsync unzip zlib1g-dev file wget \
            libgnutls28-dev libelf-dev ecj fastjar java-propose-classpath

      - name: Clone OpenWrt
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a || (echo "feeds update failed!" && exit 1)
          ./scripts/feeds install -a || (echo "feeds install failed!" && exit 1)

      - name: Copy custom config
        run: |
          cd openwrt
          cp ../ax18.config .config
          echo "CONFIG_TARGET_PREINIT_IP=\"192.168.10.1\"" >> .config
          make defconfig

      - name: Show diffconfig
        run: |
          cd openwrt
          ./scripts/diffconfig.sh

      - name: Download packages
        run: |
          cd openwrt
          make download -j$(nproc)

      - name: Build firmware
        run: |
          cd openwrt
          make -j$(nproc) V=s || (echo "Build failed!" && exit 1)

      - name: Upload firmware
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ax18-firmware
          path: openwrt/bin/targets
