name: Build ImmortalWrt AX18 (Final)

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REPO_URL: https://github.com/VIKINGYFY/immortalwrt
  REPO_BRANCH: main
  CONFIG_FILE: ax18nano.config
  THREAD_COUNT: $(nproc)
  FIRMWARE_NAME: immortalwrt-ax18
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        # 签出你自己的仓库，这样才能访问到 custom-files 目录
        uses: actions/checkout@v4

      - name: Set up environment and install dependencies
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison gawk \
            libncurses5-dev libncursesw5-dev zlib1g-dev gettext \
            libssl-dev python3 python3-distutils rsync unzip \
            wget git subversion ccache
      
      - name: Cache build files
        uses: actions/cache@v4
        with:
          path: |
            ~/ccache
            ~/immortalwrt/dl
          key: ${{ runner.os }}-immortalwrt-${{ hashFiles('**/ax18nano.config', '**/custom-files/**') }}

      - name: Set up ccache
        run: |
          mkdir -p ~/ccache
          ccache -M 5G
          ccache -s

      - name: Clone ImmortalWrt source code
        run: |
          if [ -d "immortalwrt" ]; then
            cd immortalwrt && git pull
          else
            git clone --depth=1 -b "$REPO_BRANCH" "$REPO_URL" immortalwrt
          fi
          echo "PATH=$HOME/ccache:$PATH" >> $GITHUB_ENV

      - name: Update feeds
        working-directory: ./immortalwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Apply custom configuration files
        # 这是新的核心步骤
        run: |
          # 检查自定义文件目录是否存在
          if [ -d "custom-files" ]; then
            echo "Custom files found. Copying to build root."
            # -f 强制覆盖，-r 递归复制
            cp -rf ./custom-files/* ./immortalwrt/files/
          else
            echo "No custom files found. Skipping."
          fi

      - name: Load custom configuration
        working-directory: ./immortalwrt
        run: |
          cp ../"$CONFIG_FILE" .config
          make defconfig

      - name: Download package sources
        id: download
        working-directory: ./immortalwrt
        run: |
          make download -j"$THREAD_COUNT"
          find dl -size -1024c -exec rm -f {} \;

      - name: Build firmware
        id: compile
        working-directory: ./immortalwrt
        run: |
          make -j"$THREAD_COUNT" || make -j1 V=s

      - name: Organize firmware files
        id: organize
        if: steps.compile.outcome == 'success'
        run: |
          cd immortalwrt/bin/targets/*/*
          rm -rf packages
          echo "FIRMWARE_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        if: steps.compile.outcome == 'success'
        with:
          name: ${{ env.FIRMWARE_NAME }}
          path: ${{ env.FIRMWARE_PATH }}
