name: Build OpenWrt AX18

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison gawk \
            libncurses5-dev libncursesw5-dev zlib1g-dev gettext \
            libssl-dev python3 python3-distutils rsync unzip \
            wget git ccache

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy custom config
        run: |
          cp ax18nano.config .config
          make defconfig

      - name: Download sources
        run: |
          make download -j$(nproc)

      - name: Build firmware
        run: |
          make -j$(nproc) || make -j$(nproc) V=s

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-ax18
          path: bin/targets
